# This file was generated by GoReleaser. DO NOT EDIT.
cask "letshare" do
  desc "A TUI for sharing files over local network"
  homepage "https://github.com/MuhamedUsman/letshare"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "letshare"

  on_macos do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/letshare_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "3da7d17c1e7fc84de0702006afdfecfe7bcf9340b8beb6e72cd9ae332487872f"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/letshare_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "8bed45480b562617aa42f34e5c31c58c6444be3d2a3ed246801fd395477a36ac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/letshare_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "3ee0bb9af4d9413d05355fcbdb1f1e0c27e73522ac9d65eb5eaf3c1c81057edd"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/letshare_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "02205f12342b09bd9d1894a86d4c7bfdaeb5fd569666212a56a03bf28b5fa5ec"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
       system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/letshare"]
    end
  end

  caveats do
    "This application requires:"
    "1. Administrator privileges to bind to port 80"
    "2. This application uses mDNS for automatic network discovery & publishing"
  end

  # No zap stanza required
end
