# This file was generated by GoReleaser. DO NOT EDIT.
cask "letshare" do
  desc "'A TUI for sharing files over local network'"
  homepage "https://github.com/MuhamedUsman/letshare"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "Letshare"

  on_macos do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "e4f9ad42729c531efdb0a0694abb8fa4664addd98d75ca0c5c0442a9212b1022"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "e53e006279588c174406d386d10c02893c40ca88418046646e6b593cda636d60"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "5c876f45e95f6f9265cd0b775d8f0d71282ce06e64b004e6f7c0a7f3c9c1133c"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "2c52e2680a0e60e56e3643ba36f5015ca1fb6683b74aeac60d573a72470c9604"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
       system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Letshare"]
    end
  end

  caveats do
    "This application requires:"
    "1. Administrator privileges to bind to port 80"
    "2. This application uses mDNS for automatic network discovery & publishing"
  end

  # No zap stanza required
end
