# This file was generated by GoReleaser. DO NOT EDIT.
cask "letshare" do
  desc "'A TUI for sharing files over local network'"
  homepage "https://github.com/MuhamedUsman/letshare"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "Letshare"

  on_macos do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "b5a19c2aaa3512d2ff95cdf3a080529cb93a6fd2e205a244fdea7ce27bb298e1"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "27591509de0a5d6e4e6cbb65c2d42ad84e385dedad33202834d98a8f3681a24a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "38ec6e17a4a9016e486f4aa1e76904fce5649d3ebc680a7d5c64f6369f32e84b"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "1d6ee09e5614692ab17ffd2bf7b435e16e6d90048d185d10d3858658272bfb06"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
       system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Letshare"]
    end
  end

  caveats do
    "This application requires:"
    "1. Administrator privileges to bind to port 80"
    "2. This application uses mDNS for automatic network discovery & publishing"
  end

  # No zap stanza required
end
