# This file was generated by GoReleaser. DO NOT EDIT.
cask "letshare" do
  desc "'A TUI for sharing files over local network'"
  homepage "https://github.com/MuhamedUsman/letshare"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "Letshare"

  on_macos do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "f7889bc24f57d81ecda6d0d97289e9d2a6a400741b286aadfab849bdc8540f99"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "3f2c164a8b13f4b7749a034d49c3f130669149ef4ec5ac5fc375753d53256bc3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "95da227a883275af2072807b06056baaf9677756c9ca48efafa9f4316b1328bd"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/Letshare_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "2ec4a3cbaeb5c64b9f861f5e458b4eec58cebeabb1a7e1c49b8ab69a664b31c6"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
       system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/Letshare"]
    end
  end

  caveats do
    "This application requires:"
    "1. Administrator privileges to bind to port 80"
    "2. This application uses mDNS for automatic network discovery & publishing"
  end

  # No zap stanza required
end
