# This file was generated by GoReleaser. DO NOT EDIT.
cask "letshare" do
  desc "A TUI for sharing files over local network"
  homepage "https://github.com/MuhamedUsman/letshare"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "letshare"

  on_macos do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/letshare_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "ed5a46f2690deb8a64ab3edbaf8290d8aa3926081bb972958c30a7f730f685d9"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/letshare_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "aa17a8586c897018c0c7849e46bb716997216c77f70c857391686381a14eee6b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/letshare_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "d874d7a00af17953ddab3d4b44d803653a774ac5a774e7f941ed8802eca1f0a2"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.0/letshare_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "e30e6180ce1ec68f7f829490215be23a5dac4e7d17dc250533612c333fb40017"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
       system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/letshare"]
    end
  end

  caveats do
    "This application requires:"
    "1. Administrator privileges to bind to port 80"
    "2. This application uses mDNS for automatic network discovery & publishing"
  end

  # No zap stanza required
end
