# This file was generated by GoReleaser. DO NOT EDIT.
cask "letshare" do
  desc "A TUI for sharing files over local network"
  homepage "https://github.com/MuhamedUsman/letshare"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "letshare"

  on_macos do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.1/letshare_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "c4187d9c52e7a37577f9b035b86ed9ce13bca5e181c0bfa7ba0bc720e892e715"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.1/letshare_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "67001cd4875429f91a6b13d932c23953f6125522f54cf3a97ecf04cfe7cb3472"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.1/letshare_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "962f077282e82bbb2ba8e1af71e37e7d826f1ea9d08c826ca4defa53e856c47d"
    end
    on_arm do
      url "https://github.com/MuhamedUsman/letshare/releases/download/v1.0.1/letshare_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "d53530936d923825ee1932598300cf2faad916b93005b9abe071f585aeaf96a8"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
       system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/letshare"]
    end
  end

  caveats do
    "This application requires:"
    "1. Administrator privileges to bind to port 80 (run with 'sudo letshare' if needed)"
    "2. mDNS support for automatic network discovery"
    ""
    "For setup help, see: https://github.com/MuhamedUsman/letshare#installation"
  end

  # No zap stanza required
end
